### PR TITLE
quote shortcode

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Related to https://github.com/mitodl/ocw-course-hugo-theme/issues/10

#### What's this PR do?
This PR adds the `quote.html` shortcode.  It takes 2 positional parameters, the first being the quote and the second being the author, like so:

```
{{< quote "It’s such a blast to teach [this course]." "—Dr. George Kocur" >}}
```

#### How should this be manually tested?
 - Clone this PR's branch of `ocw-course-hugo-theme` and run `npm start`
 - Convert `6-034-artificial-intelligence-fall-2010` using [this](https://github.com/mitodl/ocw-to-hugo/pull/170) branch of `ocw-to-hugo`
 - Clone `ocw-course-hugo-starter` and copy the contents of `6-034-artificial-intelligence-fall-2010.json` from the `ocw-to-hugo` output into `data/course.json` 
 - Replace `ocw-course-hugo-starter`'s `go.mod` contents with the following, replacing my path to `ocw-course-hugo-theme` with yours:
```
module github.com/mitodl/ocw-course-hugo-starter

go 1.13

replace github.com/mitodl/ocw-course-hugo-theme => /home/gumaerc/Code/ocw-course-hugo-theme

require github.com/mitodl/ocw-course-hugo-theme v1.0.1 // indirect

```
 - Run `hugo server --contentDir ~/Code/ocw-to-hugo/private/output/content/courses/6-034-artificial-intelligence-fall-2010/`, replacing  my path to `ocw-to-hugo` with yours
 - Browse to http://localhost:1313/sections/instructor-insights/teaching-heuristics/ and ensure that the instructor quotes are rendering like the screenshots below

#### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Review by noisecapella — APPROVED** [review]
Looks like the screenshot

**Comment by gumaerc** [comment]
@Ferdi @pdpinch Do you guys think it's okay to merge this as is for now until we get a full design for the quotes and adjust the appearance then?  The `ocw-to-hugo` component is blocked until we merge this.

**Comment by gumaerc** [comment]
I just had a look in invision and didn't realize that this mockup was available:

https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/442724922/preview?scrollOffset=503

@abdulkdawson @pdpinch should I style the quotes to look like they do here?

**Comment by gumaerc** [comment]
@abdulkdawson @pdpinch @Ferdi 

Updated screenshots based on the latest design:

image
image

**Comment by gumaerc** [comment]
I noticed that some other elements of the design have changed, namely the underlines under titles and the base font size.  I'll put up another PR after this to address those changes.

**Pull request merged**
